set MATLAB=C:\Program Files\MATLAB\R2016b
"C:\PROGRA~1\MATLAB\R2016b\bin\win64\gmake" -f tuske_sldrtex_packetio.mk  EXTMODE_STATIC_ALLOC=0 EXTMODE_STATIC_ALLOC_SIZE=1000000 TMW_EXTMODE_TESTING=0 ISPROTECTINGMODEL=NOTPROTECTING OPTS="-DTGTCONN -DON_TARGET_WAIT_FOR_START=1"
