% -------------------------------------------------------------------
%  Generated by MATLAB on 1-Dec-2018 20:43:30
%  MATLAB version: 9.5.0.944444 (R2018b)
% -------------------------------------------------------------------
saveVarsMat = load('stair_series.mat');

stair = saveVarsMat.stair; % <1x1 timeseries> unsupported class

clear saveVarsMat;
